[env:esp8266-serial]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool
upload_port = COM12
upload_flags = --before=no_reset
